
spring:
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:h2:~/Workspace/IdeaProjects/KReorganization/Code/Frameworks/SpringBootShiroDemo/test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    platform: h2
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true

logging:
  level:
    com.github.lh: debug
#    org.xnio: error
#    io.undertow: warn
#    org.springframework: error
#    org.springframework.web: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace